Models/DTO/LoginModel.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineLecture.Models.DTO
{
    public class LoginModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Models/DTO/RegistrationModel.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineLecture.Models.DTO
{
    public class RegistrationModel
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Username { get; set; }
        [Required]
        [RegularExpression("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*[#$^+=!*()@%&]).{6,}$", ErrorMessage = "Minimum length 6 and must contain  1 Uppercase,1 lowercase, 1 special character and 1 digit")]
        public string Password { get; set; }
        [Required]
        [Compare("Password")]
        public string PasswordConfirm { get; set; }
        public string ? Role { get; set; }
    }
}

Models/DTO/Status.cs
namespace OnlineLecture.Models.DTO
{
    public class Status
    {
        public int StatusCode { get; set; }
        public string Message { get; set; }
    }
}

Models/Domain/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace OnlineLecture.Models.Domain
{
    public class ApplicationUser : IdentityUser
    {
        public string Name { get; set; }
        public string? ProfilePicture { get; set; }
    }
}

Models/Domain/DatabaseContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace OnlineLecture.Models.Domain
{
    public class DatabaseContext : IdentityDbContext<ApplicationUser>
    {
        public DatabaseContext(DbContextOptions<DatabaseContext> options): base (options)  
        {
            
        }

        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace OnlineLecture.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AccontManagementController.cs
using Humanizer.Localisation;
using Microsoft.AspNetCore.Mvc;
using OnlineLecture.Models.Domain;

namespace OnlineLecture.Controllers
{
    public class AccontManagementController : Controller
    {
        public readonly DatabaseContext _db;
        public AccontManagementController(DatabaseContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var userList = _db.ApplicationUsers.ToList();
            return View(userList);
        }

        public async Task<IActionResult> Update(string id)
        {
            var userFromDB = _db.ApplicationUsers.FirstOrDefault(x => x.Id == id);
            return View(userFromDB);
        }

        [HttpPost]
        public IActionResult Update(ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                _db.ApplicationUsers.Update(applicationUser);
                _db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(applicationUser);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var userFromDB = _db.ApplicationUsers.FirstOrDefault(x => x.Id == id);
            return View(userFromDB);
        }

        [HttpPost]
        public IActionResult DeletePOST(string id)
        {
            var userFromDB = _db.ApplicationUsers.FirstOrDefault(x => x.Id == id);

            _db.ApplicationUsers.Remove(userFromDB);
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace OnlineLecture.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        public IActionResult Display()
        {
            return View();
        }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace OnlineLecture.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Display()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineLecture.Models;
using System.Diagnostics;

namespace OnlineLecture.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserAuthenticationController.cs
using OnlineLecture.Models.DTO;
using OnlineLecture.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace OnlineLecture.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private readonly IUserAuthenticationService _authService;
        public UserAuthenticationController(IUserAuthenticationService authService)
        {
            this._authService = authService;
        }


        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var result = await _authService.LoginAsync(model);
            if (result.StatusCode == 1)
            {
                return RedirectToAction("Display", "Dashboard");
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            model.Role = "user";
            var result = await this._authService.RegisterAsync(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await this._authService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }

        public async Task<IActionResult> Reg()
        {
            var model = new RegistrationModel
            {
                Username = "admin1",
                Email = "admin1@gmail.com",
                Name = "duy1",
                Password = "Admin@123"
            };
            model.Role = "admin";
            var result = await this._authService.RegisterAsync(model);
            return Ok(result);
        }

        //[AllowAnonymous]
        //public async Task<IActionResult> RegisterAdmin()
        //{
        //    RegistrationModel model = new RegistrationModel
        //    {
        //        Username = "admin",
        //        Email = "admin@gmail.com",
        //        Name = "duy",
        //        Password = "Admin@123"
        //    };
        //    model.Role = "admin";
        //    var result = await this._authService.RegisterAsync(model);
        //    return Ok(result);
        //}

        //[Authorize]
        //public IActionResult ChangePassword()
        //{
        //    return View();
        //}

        //[Authorize]
        //[HttpPost]
        //public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        //{
        //    if (!ModelState.IsValid)
        //        return View(model);
        //    var result = await _authService.ChangePasswordAsync(model, User.Identity.Name);
        //    TempData["msg"] = result.Message;
        //    return RedirectToAction(nameof(ChangePassword));
        //}

    }
}

Views/AccontManagement/Delete.cshtml
@model ApplicationUser

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update User</h2>
            </div>
        </div>
    </div>



    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />

            <div class="border p-3 mt-3">

                <div class="form-floating py-2 col-12">
                    <label asp-for="Name" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="Name" disabled />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <label asp-for="UserName" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="UserName" disabled />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <label asp-for="Email" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="Email" disabled />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="row mt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="AccontManagement" asp-action="Index" class="btn btn-secondary form-control">
                            Back To List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Views/AccontManagement/Index.cshtml
@model List<ApplicationUser>

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-primary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Users</h2>
            </div>
        </div>
    </div>


    <div class="card-body p-3">
        <table class="table table-bordered table-striped">
            <thead>
                <tr class="table-primary">
                    <th>ID</th>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Manipulate Data</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr class="table-light">
                        <td>@obj.Id</td>
                        <td>@obj.Name</td>
                        <td>@obj.UserName</td>
                        <td>@obj.Email</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="AccontManagement" asp-action="Update" class="btn btn-warning mx-2"
                                   asp-route-id="@obj.Id">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="AccontManagement" asp-action="Delete" class="btn btn-danger mx-2"
                                   asp-route-id="@obj.Id">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/AccontManagement/Update.cshtml
@model ApplicationUser

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update User</h2>
            </div>
        </div>
    </div>



    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />

            <div class="border p-3 mt-3">

                <div class="form-floating py-2 col-12">
                    <label asp-for="Name" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <label asp-for="UserName" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="UserName" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>

                <div class="form-floating py-2 col-12">
                    <label asp-for="Email" class="ms-2"></label>
                    <input class="form-control border-0 shadow" asp-for="Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="row mt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="AccontManagement" asp-action="Index" class="btn btn-secondary form-control">
                            Back To List
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@* @section scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
} *@

Views/Admin/Display.cshtml
@{
}
welcome, i am admin

Views/Dashboard/Display.cshtml
@{
    string username = User.Identity.Name;
}
welcome @username

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* <title>Dotnet6MvcLogin</title> *@
    <title>@ViewData["Title"]Online Lecture</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Online Lecture</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li><a href="/Dashboard/Display">Dashboard</a></li>
                @if (User.IsInRole("admin"))
                {
                    <li><a href="/Admin/Display">Admin Page</a></li>
                }
                @if (!string.IsNullOrEmpty(User.Identity.Name))
                {
                    <li><a href="/UserAuthentication/ChangePassword">ChangePassword</a></li>
                    <li><a href="/UserAuthentication/Logout">Logout</a></li>
                }
            </ul>
        </div>
    </nav>


    <div class="container">
        @RenderBody()
    </div>
</body>
</html>

Views/UserAuthentication/Login.cshtml
@model OnlineLecture.Models.DTO.LoginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
	<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>login</title>
        
<style>

form {
  border: 3px solid #f1f1f1;
  width:60%;
  margin:auto;
  margin-top:10%;
}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #aa048b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

.container {
  padding: 16px;
}

.msg{
  padding: 0px;
}


.err{
    color:red;
}
</style>
 
</head>
<body>
	
<form asp-action="Login" method="post">
  
  <div class="container">
    <label asp-for="Username"><b>Username</b></label>
    <input type="text" asp-for="Username" placeholder="Enter Username">
            <div class="msg">
            <span class="err" asp-validation-for="Username"></span>
            </div>

            

    <label asp-for="Password"><b>Password</b></label>
   <input  type="password" asp-for="Password" placeholder="Enter Password">
            <div class="msg">
            <span asp-validation-for="Password" class="err"></span>
            </div>


    @if(TempData["msg"]!=null){
                <div class="msg err">@TempData["msg"]</div>
    }

    <button type="submit">Login</button>
    <a class="text-alert" href="/UserAuthentication/Registration">Not a user? Signup</a>
  </div>
</form>

</body>
</html>

Views/UserAuthentication/Registration.cshtml
@model OnlineLecture.Models.DTO.RegistrationModel
@{
    Layout = null;
}

@* <link href="/css/bootstrap.min.css" rel="stylesheet" />
@Html.ValidationSummary() *@
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Registration</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boostrap@3.3.7/dist/css/boostrap.min.css" in
    </head>
    <body>

    </body>
</html>
<div class="container">
    <div class="row">
        <div class="col-md-6 center-block">
            <h3>Registration</h3>
            <form asp-action="Registration" method="post">
                @* <div class="form-group">
                    <label>FName*</label>
                    <input type="text" class="form-control" asp-for="FirstName"/>
                    <span class="text-danger"  asp-validation-for="FirstName"></span>
                </div>

                <div class="form-group">
                    <label>LName*</label>
                    <input type="text" class="form-control" asp-for="LastName" />
                    <span class="text-danger" asp-validation-for="LastName"></span>
                </div> *@
                <div class="form-group">
                    <label>LName*</label>
                    <input type="text" class="form-control" asp-for="Name" />
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="text" class="form-control" asp-for="Email" />
                    <span class="text-danger" asp-validation-for="Email"></span>

                </div>

                <div class="form-group">
                    <label>Username</label>
                    <input type="text" class="form-control" asp-for="Username" />
                    <span class="text-danger" asp-validation-for="Username"></span>

                </div>

                <div class="form-group">
                    <label>Password (eg. John@123)</label>
                    <input type="password" class="form-control" asp-for="Password" />
                    <span class="text-danger" asp-validation-for="Password"></span>

                </div>

                <div class="form-group">
                    <label>Password confirm</label>
                    <input type="password" class="form-control" asp-for="PasswordConfirm" />
                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>

                </div>

               
                
                @if (TempData["msg"] != null)
                {
                    <div class="form-group">
                       <span class="text-info">@TempData["msg"]</span>
                    </div>
                }

                <button type="submit" class="btn btn-info">Registration</button>
                <a class="btn btn-primary" href="/UserAuthentication/Login">Login</a>
            </form>
        </div>
    </div>
</div>